### PR TITLE
Fix for the new CameraRoll format `ph://XXXX/XX/XX`

### PR DESCRIPTION
**Pull request by netbull**
sorry for the mess with the commits... it's my first time when I play with native module...

### CODE REVIEW

**Comment by netbull** [comment]
@maxim-kolesnikov is there any change to review the PR? Currently the converter does not work with RN 60

**Comment by maxim-kolesnikov** [comment]
@netbull I can check it on weekend, but I want publish version with alpha tag name now.. 
Could you try send this path instead of using filename?

```ph://CC95F08C-88C3-4012-9D6D-64A413D254B3/L0/001/IMG_0111.HEIC```

Please look this https://github.com/maxim-kolesnikov/react-native-heic-converter/issues/3#issuecomment-509965195, I think it could work.

**Comment by netbull** [comment]
@maxim-kolesnikov thanks!

`ph://CC95F08C-88C3-4012-9D6D-64A413D254B3/L0/001/IMG_0111.HEIC` throws an error `Can't write file`

**Comment by maxim-kolesnikov** [comment]
@netbull 
```bash
yarn add react-native-heic-converter@alpha
```
or 
```json
"dependencies": {
  "react-native-heic-converter": "1.2.2-alpha.0"
}
```

**Comment by netbull** [comment]
@maxim-kolesnikov thanks, already did it :) I guess I can delete the fork now.

**Comment by maxim-kolesnikov** [comment]
@netbull 
 > ph://CC95F08C-88C3-4012-9D6D-64A413D254B3/L0/001/IMG_0111.HEIC throws an error Can't write file

Did you change folder key when try?
```
ph://XXXX/XX/XX/YOUR_IMG_FILENAME.HEIC
```
Path from CameraRoll `ph://XXXX/XX/XX/` + `YOUR_IMG_FILENAME.HEIC`

**Comment by netbull** [comment]
No, I just did ``${photo.uri}/${photo.filename}`` where `photo` is just the object from the CameraRoll

Also I tried to remove the `ph://`, but with same error.

**Comment by maxim-kolesnikov** [comment]
@netbull ok, thx

**Pull request merged**
